// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5dLOLNY9QqJmWBb2OmRJLBv5XHLd96QA',
    appId: '1:638124934146:web:de39ccd3355d2a19e4531b',
    messagingSenderId: '638124934146',
    projectId: 'restaurante-dbc6e',
    authDomain: 'restaurante-dbc6e.firebaseapp.com',
    storageBucket: 'restaurante-dbc6e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEH9LpEl6-7AhUVr0BCTvZApe9jiNxuNA',
    appId: '1:638124934146:android:851e2aa3370bc663e4531b',
    messagingSenderId: '638124934146',
    projectId: 'restaurante-dbc6e',
    storageBucket: 'restaurante-dbc6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJuMlRhwvNK_mSKvKcXRjTmbEWQLfmMKo',
    appId: '1:638124934146:ios:15082f5caa92e8b1e4531b',
    messagingSenderId: '638124934146',
    projectId: 'restaurante-dbc6e',
    storageBucket: 'restaurante-dbc6e.appspot.com',
    iosBundleId: 'com.example.learningFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJuMlRhwvNK_mSKvKcXRjTmbEWQLfmMKo',
    appId: '1:638124934146:ios:15082f5caa92e8b1e4531b',
    messagingSenderId: '638124934146',
    projectId: 'restaurante-dbc6e',
    storageBucket: 'restaurante-dbc6e.appspot.com',
    iosBundleId: 'com.example.learningFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5dLOLNY9QqJmWBb2OmRJLBv5XHLd96QA',
    appId: '1:638124934146:web:7b3e561720c45fbae4531b',
    messagingSenderId: '638124934146',
    projectId: 'restaurante-dbc6e',
    authDomain: 'restaurante-dbc6e.firebaseapp.com',
    storageBucket: 'restaurante-dbc6e.appspot.com',
  );
}
